name: matrix hello

on: [push]

jobs: 
    hello-matrix:
        runs-on: ubuntu-latest
        strategy: 
            matrix:
                jobname: [job1,job2,job3,job4]
        steps: 
            - run: echo "Hello from ${{ matrix.jobname}}!"
